apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ys7c5mrws-python
  janus-idp.io/tekton: ys7c5mrws-python
  backstage.io/kubernetes-id: ys7c5mrws-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ys7c5mrws-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
