apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ys7c5mrws-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ys7c5mrws-python 
  name: ys7c5mrws-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ys7c5mrws-python
    weight: 100 
