apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ys7c5mrws-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ys7c5mrws-python 
  name: ys7c5mrws-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ys7c5mrws-python 
